# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.spaceship_pb2 as spaceship__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spaceship_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SpaceshipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_spaceships = channel.unary_stream(
                '/spaceship.SpaceshipService/get_spaceships',
                request_serializer=spaceship__pb2.Coordinates.SerializeToString,
                response_deserializer=spaceship__pb2.Spaceship.FromString,
                _registered_method=True)


class SpaceshipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_spaceships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_spaceships': grpc.unary_stream_rpc_method_handler(
                    servicer.get_spaceships,
                    request_deserializer=spaceship__pb2.Coordinates.FromString,
                    response_serializer=spaceship__pb2.Spaceship.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceship.SpaceshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spaceship.SpaceshipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpaceshipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_spaceships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spaceship.SpaceshipService/get_spaceships',
            spaceship__pb2.Coordinates.SerializeToString,
            spaceship__pb2.Spaceship.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
